In [4]:
# numpy is used for working with numeric and scientific computing and 3D arrays

In [24]:
import numpy as np

In [25]:
l1 = [1,2,3,4]

In [26]:
n1 = np.array(l1)
# can also write np.array([1,2,3,4])

In [27]:
type(n1)

numpy.ndarray

In [28]:
l2=[9,8,7,6]
l3 =[5,6,7,8]

In [32]:
n2 = np.array([l3,l2])

In [33]:
n2

array([[5, 6, 7, 8],
       [9, 8, 7, 6]])

In [50]:
n2.shape

(2, 4)

In [52]:
n2.shape = (4,2)
n2.shape

(4, 2)

In [ ]:
n21.shape(4,2)

In [34]:
n0 = np.zeros((2,3))

In [35]:
n0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
n3= np.full((5,5),5)

In [37]:
n3

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [40]:
n4 =np.arange(10,20)
n4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
n5 = np.arange(10,50,5)

In [42]:
n5


array([10, 15, 20, 25, 30, 35, 40, 45])

In [43]:
n6 = np.random.randint(1,50,5)

In [44]:
n6

array([48,  8, 47,  1, 21])

In [54]:
np.vstack((l2,l3))

array([[9, 8, 7, 6],
       [5, 6, 7, 8]])

In [55]:
np.hstack((l2,l3))

array([9, 8, 7, 6, 5, 6, 7, 8])

In [56]:
np.column_stack((l2,l3))

array([[9, 5],
       [8, 6],
       [7, 7],
       [6, 8]])

In [57]:
np.intersect1d(l2,l3)

array([6, 7, 8])

In [58]:
np.setdiff1d(l2,l3)

array([9])

In [60]:
np.setdiff1d(l3,l2)

array([5])

In [62]:
np.sum([l2,l3])

56

In [63]:
np.sum([l2,l3],axis=0)

array([14, 14, 14, 14])

In [66]:
np.sum([l2,l3],axis=1)

array([30, 26])

In [67]:
l4 = [1,1,2,3,4]

In [68]:
np.mean(l4)

2.2

In [69]:
np.std(l4)

1.16619037896906

In [70]:
np.median(l4)

2.0

In [72]:
np.save('my_numpy',l4)

In [73]:
np.load('my_numpy.npy',)

array([1, 1, 2, 3, 4])

In [2]:
l = [1,2,2,3,0,2]
l.count(2)

3